"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Lokal kompyuterda sozlamalar .env faylidan o'qiladi.
# Docker'da .env image ichiga kirmaydi (.dockerignore), o'zgaruvchilar
# compose.yaml dagi "environment" orqali to'g'ridan-to'g'ri beriladi.
# Fayl topilmasa, load_dotenv hech narsa qilmaydi va xato bermaydi.
load_dotenv(BASE_DIR / '.env')


# Muhit o'zgaruvchilari doim matn (str) bo'ladi. Bu yordamchi funksiyalar
# ularni kerakli turga aylantiradi:
#   env_bool('DEBUG')         -> "True", "1", "yes", "on" bo'lsa True
#   env_list('ALLOWED_HOSTS') -> "a.uz,b.uz" -> ['a.uz', 'b.uz']
def env_bool(name, default='False'):
    return os.environ.get(name, default).strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(name, default=''):
    return [item.strip() for item in os.environ.get(name, default).split(',') if item.strip()]


# Maxfiy kalit: sessiya, parol tiklash havolalari va CSRF shu kalit bilan himoyalanadi.
# Serverda albatta uzun tasodifiy qiymat bo'lishi kerak.
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-local-development-key-only')

# Production'da DEBUG doim False: True bo'lsa, xato sahifasida kod va sozlamalar ko'rinib qoladi.
DEBUG = env_bool('DEBUG')

# Himoya: DEBUG o'chiq, lekin kalit standartligicha qolgan bo'lsa, Django ishga tushmaydi.
if not DEBUG and SECRET_KEY.startswith('django-insecure-'):
    raise ImproperlyConfigured('SECRET_KEY must be set in .env when DEBUG is off')

# Sayt qaysi domen yoki IP orqali ochilishiga ruxsat. Ro'yxatda yo'q domen bilan
# kelgan so'rovga Django "400 Bad Request" qaytaradi (DisallowedHost).
ALLOWED_HOSTS = env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1')

# HTTPS'da forma yuborilganda (POST) CSRF tekshiruvi ishonadigan manzillar.
# Masalan: https://lms.example.uz
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')

# HTTPS sozlamalari faqat sertifikat olingandan keyin yoqiladi (.env: USE_HTTPS=True).
#   SECURE_PROXY_SSL_HEADER — so'rov HTTPS ekanini Django nginx yuborgan
#                             X-Forwarded-Proto sarlavhasidan biladi. Usiz
#                             cheksiz redirect halqasi paydo bo'ladi
#   SECURE_SSL_REDIRECT     — http:// so'rovlarni https:// ga yo'naltirish
#   *_COOKIE_SECURE         — cookie faqat shifrlangan ulanish orqali yuboriladi
#   SECURE_HSTS_SECONDS     — brauzer shu muddat davomida saytga faqat HTTPS
#                             orqali kiradi. Avval kichik qiymat bilan sinaladi
USE_HTTPS = env_bool('USE_HTTPS')

if USE_HTTPS:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', 31536000))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'accounts',
    'courses',
]

AUTH_USER_MODEL = 'accounts.CustomUser'

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'accounts:dashboard'
LOGOUT_REDIRECT_URL = 'accounts:login'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DB_NAME berilgan bo'lsa — PostgreSQL, berilmagan bo'lsa — SQLite.
# Docker'da DB_HOST=db (compose.yaml dagi servis nomi), lokal kompyuterda localhost.
# CONN_MAX_AGE=60 — bazaga ulanish har so'rovda yangidan ochilmaydi,
# 60 soniya qayta ishlatiladi.
if os.environ.get('DB_NAME'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['DB_NAME'],
            'USER': os.environ['DB_USER'],
            'PASSWORD': os.environ['DB_PASSWORD'],
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
            'CONN_MAX_AGE': 60,
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'uz'

TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# STATICFILES_DIRS — dasturchi yozgan CSS/JS (static/ papka).
# STATIC_ROOT      — "collectstatic" hamma static fayllarni shu papkaga yig'adi.
#                    Docker'da bu papkaga static_data volume ulanadi va nginx
#                    fayllarni shu yerdan beradi.
STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# MEDIA_ROOT — foydalanuvchilar yuklagan fayllar. Docker'da media_data volume.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Loglar.
# DEBUG=False bo'lganda Django standart holatda 500 xatolar tafsilotini
# (traceback) hech qayerga yozmaydi. Bu blok WARNING va undan jiddiy
# xabarlarni ekranga (stderr) chiqaradi. Docker ularni yig'adi:
#   docker compose logs web
# Filtr sababli DEBUG=True (lokal runserver) holatida chiqish avvalgidek qoladi.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'filters': ['require_debug_false'],
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}
